### ISSUE TITLE
your token is showing?

### ISSUE THREAD

**Issue by luphoria** [Tomato6966/distube-music-bot#4]
_might_ want to refresh your token my guy, it's sorta in the source code

**Comment by fmayam** [comment]
he always refreshes it. that token is for his test bot anyways

**Comment by luphoria** [comment]
it is also in two other bots on this account. idk, either way you really should not have any tokens in the source code
i never tested the token, however the fact that one is there at all is a bit concerning

**Comment by Tomato6966** [comment]
All tokens which i put on github are fake and just template for users who dont know how a discord token looks like
